### ISSUE TITLE
Double-scrolling or height mismatches on pages with marginal notes in Chrome

### ISSUE THREAD

**Issue by david-christiansen** [leanprover/reference-manual#128]
On Zulip, it was noticed that marginal notes are causing a problem for scrolling in Chrome: https://leanprover.zulipchat.com/#narrow/channel/113488-general/topic/Discussion.20thread.20for.20Lean.20Language.20Reference/near/479299508

Screenshots from the thread:
![image](https://github.com/user-attachments/assets/db94b5ae-8d0e-44ef-950d-f1146904d534)

![image](https://github.com/user-attachments/assets/209c4773-cc06-4c26-ac96-a93c43c368a6)

**Comment by frangio** [comment]
https://github.com/leanprover/verso/pull/211 fixes the double scrolling.
