### ISSUE TITLE
CSS: inconsistent font sizes on mobile

### ISSUE THREAD

**Issue by david-christiansen** [leanprover/reference-manual#137]
Some fonts are tiny on mobile phone screens:
![Screenshot_20241104-113055](https://github.com/user-attachments/assets/654848fd-5acd-47d8-aebc-c8038163fd48)
In particular:
![Screenshot_20241104-113055-annot](https://github.com/user-attachments/assets/9a1c263a-0323-41fb-be1a-2a78323b346e)
![Screenshot_20241104-113112-annot](https://github.com/user-attachments/assets/b95fdaa8-e672-4f11-9748-dc6b6b1b95e3)

They should all be the same size, as they are on desktop browsers.

**Comment by jakobvase** [comment]
Don't use `em` anywhere :) Only use `rem`.

Other than that, I think this is also fixed by adding the extra header mentioned in #140. But let's have a look once all the other changes are implemented.

**Comment by david-christiansen** [comment]
Fixed in #148. Thanks for the help!
