### ISSUE TITLE
Where does head come from in Recursive Equational Lemmas?

### ISSUE THREAD

**Issue by nielsvoss** [leanprover/reference-manual#182]
In the dropdown _Recursive Equational Lemmas_ of Section 2.4. Elaboration Results of https://lean-lang.org/doc/reference/latest/Elaboration-and-Compilation/

In:
```lean
everyOther.eq_unfold.{u} :
  @everyOther.{u} = fun {α} x =>
    match x with
    | [] => []
    | [x] => [x]
    | x :: head :: xs => x :: everyOther xs
```
and
```lean
everyOther.eq_def.{u} {α : Type u} :
  ∀ (x : List α),
    everyOther x =
      match x with
      | [] => []
      | [x] => [x]
      | x :: head :: xs => x :: everyOther xs
```
and
```
everyOther.eq_3.{u} {α : Type u} (x_1 head : α) (xs : List α) :
  everyOther (x_1 :: head :: xs) = x_1 :: everyOther xs
```

Is the name `head` necessary, or can it be replaced with `_` (in all but the last example)? Or is it automatically generated? I was confused the first time I read this, because I didn't know where `head` came from, given that it wasn't a constructor name.

**Comment by david-christiansen** [comment]
It is automatically generated, but I think it's OK for exposition to pick slightly nicer names here. Thanks!
