### ISSUE TITLE
Is intensional equality always decidable?

### ISSUE THREAD

**Issue by nielsvoss** [leanprover/reference-manual#189]
**Describe the error**

In [3.2.1.5. Extensionality](https://lean-lang.org/doc/reference/latest/find/?domain=Verso.Genre.Manual.section&name=function-extensionality)
> Intensional equality is mechanically decidable; Lean's type checker can decide whether two functions are intensionally equal.

Why is it incorrect and/or confusing?

Can Lean always decide whether two functions are equal, or just almost always? I thought that type checking in Lean was technically undecidable, so it might be worth clarifying if intentional equality is _always_ decidable, or just decidable except for a few extremely pathological examples.

**Comment by david-christiansen** [comment]
This is a great clarification. Thank you!
