### ISSUE TITLE
Incorrect Relative Path of Top Link

### ISSUE THREAD

**Issue by SnO2WMaN** [leanprover/reference-manual#220]
**Describe the bug**

![image](https://github.com/user-attachments/assets/5e082c6e-4437-4de9-a38d-c4d9c74aa722)

Every top link (see image) might be supposed to be `https://lean-lang.org/doc/reference/latest/`, However now is incorrect, it leads to `https://lean-lang.org/doc/reference/latest/doc/reference/latest/`. 

This might be caused auto-generated template injection, but I don't know where is wrong in this project,

**Demonstration**

Click Lean logo on https://lean-lang.org/doc/reference/latest .

**Comment by david-christiansen** [comment]
Thanks! Fixed in #221 .
