### ISSUE TITLE
Pages stop loading with "Page not found"

### ISSUE THREAD

**Issue by philnguyen** [leanprover/reference-manual#224]
I was able to load all the links in the reference when it was first out. But today when I tried again, many pages fail to load with a message "Page not found" (e.g. [https://lean-lang.org/io/#io](https://lean-lang.org/io/#io))
![Screenshot 2024-12-21 at 9 03 29 PM](https://github.com/user-attachments/assets/a874ed71-ecfd-4663-9454-d304d97fd10f)

**Comment by david-christiansen** [comment]
Thanks so much for the report! It seems to be an issue with our web host. I've put a workaround in place, and will evaluate a more permanent solution after the holidays.

Much appreciated!
