### ISSUE TITLE
Describe `instance` declarations

### ISSUE THREAD

**Issue by david-christiansen** [leanprover/reference-manual#62]
Including:
 * Instance priorities
 * Instance names

**Comment by hrmacbeth** [comment]
One point perhaps worth describing here: what does it mean to make something a "default instance"?

**Comment by david-christiansen** [comment]
I believe it's been sufficiently described - please let me know if not!

**Comment by hrmacbeth** [comment]
Yes, and I learned a lot from this new chapter!

One minor point for possible clarification, from 3.6.3.1:
> For default instances, the input parameters do not need to be fully known, and may be instantiated by the instances parameter values. 

I didn't manage to parse this sentence -- I wondered whether (e.g.) it was a typo for "instance's parameter values"?
